name:                mdth
version:             0.1.0.0
github:              "Nutr1t07/mdth"
license:             BSD3
author:              "Nutr1t07"
maintainer:          "Nutr1t07@outlook.com"
copyright:           "2020 Nutr1t07"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Nutr1t07/mdth#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- attoparsec
- word8
- hspec
- QuickCheck
- stringsearch

library:
  source-dirs: src

executables:
  mdth-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mdth

tests:
  mdth-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mdth
